services:
  - 'mysql:8.0'
variables:
  MYSQL_HOST: localhost
  MYSQL_DATABASE: test
  MYSQL_CI_URL: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?verifyServerCertificate=false&useSSL=false&requireSSL=false
  MYSQL_ROOT_PASSWORD: root
image: "maven:3.5.2-jdk-8"
maven-test:
           script: "mvn test"
           stage: test
stages:
       - test